'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class German
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FlashcatUSB.German", GetType(German).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Board-Firmware-Version.
        '''</summary>
        Friend Shared ReadOnly Property cnts_avrver() As String
            Get
                Return ResourceManager.GetString("cnts_avrver", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Verbunden mit Gerät.
        '''</summary>
        Friend Shared ReadOnly Property cnts_device() As String
            Get
                Return ResourceManager.GetString("cnts_device", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash-Speicher-Namen.
        '''</summary>
        Friend Shared ReadOnly Property cnts_flashname() As String
            Get
                Return ResourceManager.GetString("cnts_flashname", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash-Speichergröße.
        '''</summary>
        Friend Shared ReadOnly Property cnts_flashsize() As String
            Get
                Return ResourceManager.GetString("cnts_flashsize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash-Speicher-Typ.
        '''</summary>
        Friend Shared ReadOnly Property cnts_flashtype() As String
            Get
                Return ResourceManager.GetString("cnts_flashtype", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Geräte-Modus.
        '''</summary>
        Friend Shared ReadOnly Property cnts_mode() As String
            Get
                Return ResourceManager.GetString("cnts_mode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Skript aktiv.
        '''</summary>
        Friend Shared ReadOnly Property cnts_script() As String
            Get
                Return ResourceManager.GetString("cnts_script", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fehler: Die Hex-Datei Daten sind größer als die Größe des DFU-Speicher.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avr_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_avr_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Löschen des AVR Flash-Speichers.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avr_err2() As String
            Get
                Return ResourceManager.GetString("fcusb_avr_err2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sende AVR DFU Löschbefehl.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avr_err3() As String
            Get
                Return ResourceManager.GetString("fcusb_avr_err3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fehler: AVR Flash Erase ist fehlgeschlagen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avr_err4() As String
            Get
                Return ResourceManager.GetString("fcusb_avr_err4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fehler: AVR Flash Schreiben ist fehlgeschlagen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avr_err5() As String
            Get
                Return ResourceManager.GetString("fcusb_avr_err5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AVR DFU Befehl erfolgreich.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avr_sucess() As String
            Get
                Return ResourceManager.GetString("fcusb_avr_sucess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AVR Flash erfolgreich geschrieben.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avr_writedone() As String
            Get
                Return ResourceManager.GetString("fcusb_avr_writedone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Neue AVR Firmware wurde programmiert (klicken Sie auf &apos;Start Anwendung&apos; um zu beginnen).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avr_writedonegui() As String
            Get
                Return ResourceManager.GetString("fcusb_avr_writedonegui", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Starte AVR Flash schreiben ({0} Bytes).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avrwrite() As String
            Get
                Return ResourceManager.GetString("fcusb_avrwrite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Basisadresse.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_baseaddress() As String
            Get
                Return ResourceManager.GetString("fcusb_baseaddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stornieren.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cancel() As String
            Get
                Return ResourceManager.GetString("fcusb_cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash-Basis-Adresse: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_base() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_base", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ({0} Bit-Bus).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_bitbus() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_bitbus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash-Beschreibung: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_desc() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_desc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CFI Löschvorgang erfolgreich.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_erasecomplete() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_erasecomplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Löschen von Flash-CFI (dies könnte einen Moment dauern).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_erasing() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_erasing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Konnte Gerät in JEDEC-Modus nicht öffnen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Installierte CFI kompatibles Flash-Gerät auf: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_founddev() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_founddev", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ändere Parameter für bestehenden Bereich: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_info1() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_info1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Schnittstelle.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_interface() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_interface", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash-JEDEC-ID: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_jedecid() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_jedecid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Programmiermodus.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_pmode() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_pmode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (Unbekannt).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_unknown() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_unknown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Programmiermodus: EXT I/O.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cmos_progmode() As String
            Get
                Return ResourceManager.GetString("fcusb_cmos_progmode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB betriebsbereit im EXT I/O-Modus.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cmos_ready() As String
            Get
                Return ResourceManager.GetString("fcusb_cmos_ready", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Geräte im EXT I/O-Modus verbunden, Firmware-Version: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cmos_ver() As String
            Get
                Return ResourceManager.GetString("fcusb_cmos_ver", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wählen Sie das zu installierende  AVR Firmware-Programm aus.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_common_avrtoprog() As String
            Get
                Return ResourceManager.GetString("fcusb_common_avrtoprog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wählen Sie einen Dateipfad aus, um das Konsolen Protokoll zu speichern.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_console_save() As String
            Get
                Return ResourceManager.GetString("fcusb_console_save", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gerät in den DFU-Bootloader-Modus geschaltet.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_dfu_conn() As String
            Get
                Return ResourceManager.GetString("fcusb_dfu_conn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Datei: Keine Datei geladen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_dfu_file_default() As String
            Get
                Return ResourceManager.GetString("fcusb_dfu_file_default", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Datei laden.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_dfu_loadfile() As String
            Get
                Return ResourceManager.GetString("fcusb_dfu_loadfile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to programmieren.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_dfu_progfile() As String
            Get
                Return ResourceManager.GetString("fcusb_dfu_progfile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB betriebsbereit für den DFU-Modus.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_dfu_ready() As String
            Get
                Return ResourceManager.GetString("fcusb_dfu_ready", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Starte Anwendung.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_dfu_startprog() As String
            Get
                Return ResourceManager.GetString("fcusb_dfu_startprog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Keine Verbindung zu FlashcatUSB.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_disconnected() As String
            Get
                Return ResourceManager.GetString("fcusb_disconnected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fehler bei Abfrage der Board-Firmware-Version.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bitte aktualisieren Sie die AVR-Firmware auf {0} oder neuer.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_err2() As String
            Get
                Return ResourceManager.GetString("fcusb_err2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB Bord hat eine veraltete Firmware.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_err3() As String
            Get
                Return ResourceManager.GetString("fcusb_err3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB konnte kein Verbindung zum Ziel über JTAG aufbauen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_err4() As String
            Get
                Return ResourceManager.GetString("fcusb_err4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kann Wert nicht setzten (ungültige Eingabe).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_err5() As String
            Get
                Return ResourceManager.GetString("fcusb_err5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kann Wert nicht setzten (Wert ist größer als 1 Byte).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_err6() As String
            Get
                Return ResourceManager.GetString("fcusb_err6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kann Wert nicht setzen (Wert ist größer als 4 Bytes).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_err7() As String
            Get
                Return ResourceManager.GetString("fcusb_err7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fehler: Datei ist beschädigt oder keine AVR Hex-Datei.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_err8() As String
            Get
                Return ResourceManager.GetString("fcusb_err8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Datei: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_file() As String
            Get
                Return ResourceManager.GetString("fcusb_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Abbruch duch Benutzer. Es wurden keine Daten gespeichert.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_filesave_canceled() As String
            Get
                Return ResourceManager.GetString("fcusb_filesave_canceled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} erfolgreich auf der Festplatte gespeichert.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_filesave_sucess() As String
            Get
                Return ResourceManager.GetString("fcusb_filesave_sucess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Konvertierte Daten im Intel hex Format zum Speichern eingelesen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_filesave_tohex() As String
            Get
                Return ResourceManager.GetString("fcusb_filesave_tohex", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wählen Sie einen Speicherort und das Output-Daten-Format.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_filesave_type() As String
            Get
                Return ResourceManager.GetString("fcusb_filesave_type", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kann Daten nicht auf Flash schreiben (out of bounds).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_flasherr1() As String
            Get
                Return ResourceManager.GetString("fcusb_flasherr1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Datei: Aktuell keine Datei geladen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_hex_nofile() As String
            Get
                Return ResourceManager.GetString("fcusb_hex_nofile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Initialisiere EJTAG engine.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_initjtag() As String
            Get
                Return ResourceManager.GetString("fcusb_initjtag", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Geräte im JTAG-Modus verbunden: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_conn() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_conn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JTAG: Reset Befehl an Prozessor gesendet.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_cpureset() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_cpureset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JTAG: Prozessor im Debug Modus.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_debugon() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_debugon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zielgerät unterstützt DMA-Modus.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_dma() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_dma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Löschvorgang abgeschlossen!.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_erasecomplete() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_erasecomplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fehler beim Verbinden zum Zielgerät.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Es konnte keine Verbindung zum Gerät EJTAG hergestellt werden.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_err2() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_err2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash gefunden in: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_foundat() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_foundat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CFI: Kompatibles Flash gefunden in: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_foundcfi() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_foundcfi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JTAG: IR Länge auf {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_irlen() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_irlen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zielgerät unterstütz keinen DMA-Modus.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_nodma() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_nodma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash konnte nicht gefunden werden.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_notfound() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_notfound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JTAG: Gerät unterstützt nur non-DMA (PrAcc)-Modus, aber non-pracc Firmware ist im FlashcatUSB geladen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_praccmode() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_praccmode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB betriebsbereit im JTAG-Modus.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_ready() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_ready", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Suche nach CFI kompatible Flash-Medium.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_searchcfi() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_searchcfi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Suche nach CFI-Flash @ {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_searchcfiat() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_searchcfiat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JTAG: SPI Flash-Speicher gefunden ({0}).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_spidetected() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_spidetected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Löschen des gesamten SPI-Flash (dies könnte einen Moment dauern).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_spierasing() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_spierasing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JTAG: SPI-Register zurückgegeben {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_spiregret() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_spiregret", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JTAG-Engine Setup erfolgreich.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtagsetup() As String
            Get
                Return ResourceManager.GetString("fcusb_jtagsetup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Länge.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_length() As String
            Get
                Return ResourceManager.GetString("fcusb_length", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LibUsbDotNet Version: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_libusb_ver() As String
            Get
                Return ResourceManager.GetString("fcusb_libusb_ver", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Adresse.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_address() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_address", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Schreibvorgang durch Benutzer abgebrochen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_cancelled() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_cancelled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wählen Sie die zu schreibende Datei aus, in {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_choosefile() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_choosefile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fehler, Datei nicht vorhanden oder enthält keine Daten.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fehler beim Versuch, Daten zu lesen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_err2() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_err2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Datei gewählt, schreibe {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_filechosen() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_filechosen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Datei zum Schreiben geöffnet: {0} (binäre Hex-Format), Gesamtgröße der Datei: {1} Bytes.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_opened_bin() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_opened_bin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Datei zum Schreiben geföffnet: {0} (Intel Hex-Format), Gesamtgröße der Datei: {1} Bytes.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_opened_intel() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_opened_intel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lesevorgang abgebrochen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_readcanceled() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_readcanceled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lesevorgang abgeschlossen, bitte wählen Sie Speicherort und Format-Typ.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_readcomplete() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_readcomplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gewählter Bereich gelesen von {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_readfrom() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_readfrom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Starte Speicher Lese-Vorgang.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_readstart() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_readstart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wählen Sie den Bereich, um die Daten zu schreiben {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_selectwriterange() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_selectwriterange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lesevorgang durch Benutzer abgebrochen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_usercanceledread() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_usercanceledread", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Abbruch durch Benutzer. Keine Daten geschrieben nach {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_usercanwrite() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_usercanwrite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash-Schreib-Vorgang abgebrochen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_writecanceled() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_writecanceled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Schreibvorgang abgeschlossen: {0} Bytes geschrieben..
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_writecomplete() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_writecomplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Starte Speicher Schreib-Vorgang.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_writestart() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_writestart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Schreibe Datei {0} in {1} ({2} Bytes zu schreiben.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_writing() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_writing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Speicherbaustein.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memdev() As String
            Get
                Return ResourceManager.GetString("fcusb_memdev", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Starte Speicher Lese-Vorgang von {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_beginread() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_beginread", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bulk-Erase wird nicht von DRAM-Geräte unterstützt.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_dram_notsup() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_dram_notsup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Speicher Initialisierung: Fehlgechlagen - Initialisierung der Geräteparameter fehlgeschlagen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SPI-Flash kann nicht erkannt werden  (API für aktuelle MCU nicht geladen).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_err2() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_err2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Speicher Initialisierung: Fehlgeschlagen - Keine Verbindungsaufbau zum PrAcc Speicher-Interface möglich (AVR-Firmware wird nicht unterstützt).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_nopraccsupport() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_nopraccsupport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lesevorgang abgeschlossen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_readdone() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_readdone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Startadresse: {0} ({1}) Länge: {2} &quot;.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_startaddr() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_startaddr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prüfe geschriebene Daten in {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_verify() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_verify", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fehler: Flashüberprüfung las eine inkorrekte Anzahl von Bytes zurück.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_verifyerr1() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_verifyerr1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Adresse {0}: {1} schrieb und las {2} ({3} Diskrepanz/en) ).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_verifyerr2() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_verifyerr2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fehler: Datenüberprüfung bei {0} ist fehlgeschlagen!.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_verifyfailed() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_verifyfailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Die Verifizierung der Daten war erfolgreich.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_verifyokay() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_verifyokay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Daten können nicht geschrieben werden (Gerät im Zustand read-only).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_write_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_write_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Schreiben von Adresse {0} mit {1} Bytes ({2}).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_writeaddr() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_writeaddr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash-Vorgang abgeschlossen!.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_writecomplete() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_writecomplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Schreib-Vorgang abgeschlossen, geschrieben {0} Bytes..
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_writedone() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_writedone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} Bytes in {1} Sekunden geschrieben, {2} Bytes / s.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_writespeed() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_writespeed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AVR-Firmware.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_avrfw() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_avrfw", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Konsole.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_console() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_console", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aktuelles Skript.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_cscript() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_cscript", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Suche Chip.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_detectdevice() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_detectdevice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ausgang.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_exit() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_exit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sprache.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_language() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_language", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lade skript.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_loadscript() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_loadscript", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Main.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_main() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_main", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Skript.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_script() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_script", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Einstellungen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_settings() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_settings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Automatische Einstellungen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_auto() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_auto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bit-Reihenfolge.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_bitorder() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_bitorder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chip Löschen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_chiperase() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_chiperase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chip Größe.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_chipsize() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_chipsize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Taktteiler.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_clodiv() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_clodiv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SPI Gerät Befehle.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_devcmds() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_devcmds", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aktiviere Schreibstatus.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_enwrstatus() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_enwrstatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lösch Größe.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_erasesize() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_erasesize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Verwenden Sie die Werte aus dem Datenblatt des Chips.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_info() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_info", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Programm-Modus.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_pmode() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_pmode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Page Programm.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_pp() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_pp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lesen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_read() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_read", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status lesen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_rstatus() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_rstatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sektor Löschen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_serase() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_serase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SPI-Modus.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_spimode() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_spimode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Manuelle Einstellungen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_usesettings() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_usesettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Write Enable.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_we() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_we", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Schreib-Status.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_wstatus() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_wstatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SPI-Einstellungen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spisettings() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spisettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_status() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_status", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Entlade skript.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_unloadscript() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_unloadscript", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Schreibvorgang überprüfen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_verify() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_verify", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Geräte verbunden durch NAND over SPI-Modus.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nand_conn() As String
            Get
                Return ResourceManager.GetString("fcusb_nand_conn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB betriebsbereit für NAND-Modus.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nand_ready() As String
            Get
                Return ResourceManager.GetString("fcusb_nand_ready", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Programmierung neuer AVR-Firmware.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_newavrfw() As String
            Get
                Return ResourceManager.GetString("fcusb_newavrfw", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (Kein Flash erkannt).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_noflash() As String
            Get
                Return ResourceManager.GetString("fcusb_noflash", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Daten erfolgreich gelesen und analysiert.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nonvol_dataread() As String
            Get
                Return ResourceManager.GetString("fcusb_nonvol_dataread", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fehler: Keinen CFG Bereich gefunden!.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nonvol_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_nonvol_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fehler beim Laden von Non-Vol Daten.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nonvol_err2() As String
            Get
                Return ResourceManager.GetString("fcusb_nonvol_err2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (Nicht gefunden).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nonvol_notfound() As String
            Get
                Return ResourceManager.GetString("fcusb_nonvol_notfound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lese Non-Vol-Konfigurationsdaten.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nonvol_readingnonvol() As String
            Get
                Return ResourceManager.GetString("fcusb_nonvol_readingnonvol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Schreibe Non-Vol-Konfiguration ins Flash.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nonvol_writing() As String
            Get
                Return ResourceManager.GetString("fcusb_nonvol_writing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fertig. Non-Vol-Konfiguration aktualisiert.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nonvol_wrote() As String
            Get
                Return ResourceManager.GetString("fcusb_nonvol_wrote", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_okbutton() As String
            Get
                Return ResourceManager.GetString("fcusb_okbutton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bereich:.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_range() As String
            Get
                Return ResourceManager.GetString("fcusb_range", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lesen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_Read() As String
            Get
                Return ResourceManager.GetString("fcusb_Read", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ausgeführt auf: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_running() As String
            Get
                Return ResourceManager.GetString("fcusb_running", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Suche nach einem Gerätspezifischem Skript zum automatisch laden.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_script_check() As String
            Get
                Return ResourceManager.GetString("fcusb_script_check", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Skript {0} erfolgreich geladen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_script_loaded() As String
            Get
                Return ResourceManager.GetString("fcusb_script_loaded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lade Gerät spezifisches Skript: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_script_loading() As String
            Get
                Return ResourceManager.GetString("fcusb_script_loading", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Keine Skript-Datei verfügbar.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_script_none() As String
            Get
                Return ResourceManager.GetString("fcusb_script_none", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Skript kann nicht geladen werden (Datei wurde nicht gefunden).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_script_notexist() As String
            Get
                Return ResourceManager.GetString("fcusb_script_notexist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wählen Sie das zu öffnende FlashcatUSB Skript aus.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_script_open() As String
            Get
                Return ResourceManager.GetString("fcusb_script_open", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Das Skript {0} wurde entladen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_script_unload() As String
            Get
                Return ResourceManager.GetString("fcusb_script_unload", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Verbunden mit Flash.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_connflash() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_connflash", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Für Lese-Schreib-Support E-Mail an contact@embeddedcomputers.net mit RDID/REMS.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_email() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_email", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash Erase in {0} Sekunden abgeschlossen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_erasecomplete() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_erasecomplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Löschen des gesamten Flashs, Gesamtgröße: {0} Bytes (dies kann einen Moment dauern).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_erasingbulk() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_erasingbulk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB im SPI-Modus angeschlossen, aber kein Flash erkannt.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB erkannte SPI Gerät, dieser wird jedoch zur Zeit noch nicht unterstützt.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_err2() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_err2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SPI-Flash Größe muss mindestens 512Kbit sein.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_err3() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_err3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SPI-Flash Größe muss ein Vielfaches von einem Megabit sein.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_err4() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_err4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Keine Verbindung zu einem SPI kompatiblen Gerät.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_err5() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_err5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash-Speicher gefunden: {0} ({1} Bytes).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_flashdetected() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_flashdetected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fehler beim Festlegen des SPI-Modus, Modus nicht unterstützt: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_modenotsupported() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_modenotsupported", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SPI-Modus auf auto konfiguriert.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_modesetauto() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_modesetauto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SPI-Modus auf {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_modesetto() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_modesetto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gerät im SPI-Modus verbunden.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_openinmode() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_openinmode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Programmiermodus: SPI (schnell-Modus).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_progmode() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_progmode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB betriebsbereit im SPI-Modus.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_ready() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_ready", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scannen für SPI-Flash.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_scanning() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_scanning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Verwende benutzerdefinierte Einstellungen aus SPI Einstellungen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_usingcustom() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_usingcustom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Geräte im SPI-Modus verbunden, Firmware-Version: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_ver() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_ver", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB Status: Verbunden.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_status_connected() As String
            Get
                Return ResourceManager.GetString("fcusb_status_connected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB Status: Getrennt.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_status_disconnect() As String
            Get
                Return ResourceManager.GetString("fcusb_status_disconnect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to HALT.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_stop() As String
            Get
                Return ResourceManager.GetString("fcusb_stop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Software wartet bis Gerät über USB angeschlossen wurde.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_waitingforusb() As String
            Get
                Return ResourceManager.GetString("fcusb_waitingforusb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Willkommen bei FlashcatUSB Interface-Software, build: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_welcome() As String
            Get
                Return ResourceManager.GetString("fcusb_welcome", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Willkommen bei FlashcatUSB!.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_welcome_status() As String
            Get
                Return ResourceManager.GetString("fcusb_welcome_status", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Schreiben.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_Write() As String
            Get
                Return ResourceManager.GetString("fcusb_Write", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Geschwindigkeit.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_xferspeed() As String
            Get
                Return ResourceManager.GetString("fcusb_xferspeed", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
